# Numpy exercises


#### 1. Import the numpy package under the name `np`

#### Import արեք numpy module-ը np անունով:

In [1]:
import numpy as np

#### 2. Create a numpy array of size 10 filled with zeros. 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array:

In [2]:
arr_zeros = np.zeros(10)

#### 3.  How to get the documentation of the numpy add function? 

#### Նայեք numpy-ի add ֆունկցիայի դոկումենտացիան:

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

#### 4.  Create a numpy array of size 10 filled with zeros but the fifth value is 1 

#### Ստեղծեք 10 չափի 0-ներով լցված numpy array, որի 5րդ արժեքը 1 է:

In [4]:
arr = np.zeros(10)
arr[5] = 1

#### 5.  Create a numpy array with values ranging from 10 to 49

#### Ստեղծեք 10-ից 49 հաջորդական թվերով numpy array:

In [5]:
arr_1 = np.arange(10,50)
arr_1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 6.  Reverse the numpy array ranging from 0 to 50. 

#### Ստեղծեք 0-ից 50 հաջորդական թվերով numpy array և տպեք այն շրջած ձևով:

In [6]:
reverse_arr = np.arange(51)
print(reverse_arr[::-1])

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


#### 7.  Create a 3x3 matrix with values ranging from 0 to 8 

#### Ստեղծեք 0-ից 8 հաջորդական թվերով 3x3 numpy array

In [7]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### Տրված է \[1,2,0,0,4,0\] numpy array-ը, գտեք ոչ-զրոյական արժեքներով տարրերի կոորդինատները:

In [8]:
given_array = np.array([1,2,0,0,4,0])
print(given_array.nonzero())

(array([0, 1, 4]),)


#### 9. Create a 3x3x3 array with random integers from 1 to 20

#### Ստեղծեք 1-ից 20 պատահական թվերով լցված (3x3x3) չափանի numpy array:

In [9]:
tensor = np.random.randint(20, size = (3,3,3))
print(tensor)

[[[ 7  3 15]
  [17 11 17]
  [18  9 17]]

 [[14  6 19]
  [12  5  4]
  [10 17 18]]

 [[16  9  9]
  [11  4  0]
  [ 9 11  6]]]


#### 10. Create a 10x10 array with random values and find the minimum and maximum values 

#### Ստեղծեք պատահական թվերով լցված (10x10) չափանի numpy array ու տպեք դրա փոքրագույն ու մեծագույն արժեքները:

In [10]:
matrix_10 = np.random.random((10,10))
print("min value:", matrix_10.min())
print("max value:", matrix_10.max())

min value: 0.007097896814074578
max value: 0.982600201781805


#### 11. Create a random vector of size 30 and find the mean value 

#### Ստեղծեք 30 չափանի պատահական թվերով լցված numpy array ու տպեք դրա միջին արժեքը:

In [11]:
arr_30 = np.random.random(30)
print("Min value:", arr_30.min())

Min value: 0.01570518344542826


#### 12. Given a 1D array ranging from 0 to 10, print all the elements which are between 3 and 8. 

#### Ստեղծեք 0-ից 10 հաջորդական թվերով numpy array: Տպեք բոլոր արժեքները, որոնք 3-ից 8 միջակայքում են:

In [12]:
arr10 = np.arange(11)
print(arr10)
print(arr10[(3 < arr10)&(arr10 < 8)])

[ 0  1  2  3  4  5  6  7  8  9 10]
[4 5 6 7]


#### 13. Given a 1D array of 20 random integers from 0 to 10, multiply the values that are less than 5 by 2 and print the resulting array.

#### Ստեղծեք 1-ից 10 պատահական ամբողջ թվերով լցված 20 չափանի numpy array: Բազմապատկեք 5-ից փոքր արժեք ունեցող տարերրը 2-ով ու տպեք արդյունքում ստացված array-ը:

In [13]:
arr20 = np.random.randint(10, size = (20))
print(arr20)
newarr = arr20[np.where(arr20 < 5)]*2
print(newarr)

[6 4 1 3 8 4 5 1 0 7 9 6 6 2 7 5 0 7 0 4]
[8 2 6 8 2 0 4 0 0 8]


#### 14. Given the 1D array [1, 5, 6, 2, -2, 23, 45], find the indices of the array elements that are divisible by 2.

#### Տրված է [1, 5, 6, 2, -2, 23, 45] numpy array-ը, գտեք 2-ի բաժանվող տարրերի կոորդինատները:

In [14]:
arr14 = np.array([1, 5, 6, 2, -2, 23, 45])
print(np.where(arr14%2==0))

(array([2, 3, 4]),)


#### 15. Given a 1D array ranging from 0 to 20, print all the elements which are divisible by 3. 

#### Ստեղծեք 1-ից 20 հաջորդական թվերով լցված numpy array, տպեք բոլոր 3-ի բաժանվող տարրերի արժեքները:

In [15]:
arr15 = np.arange(1, 21)
print(arr15[np.where(arr15 %3 == 0)])

[ 3  6  9 12 15 18]


#### 16. Create a 5x5 numpy array with each row values ranging from 0 to 4 

#### Ստեղծեք 5x5 numpy array, որի ամեն տող իրենից ներկայացնում է 0-ից 4 հաջորդական թվեր:

In [16]:
np.zeros((5, 5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 17. Create a 3x5 numpy array filled with random numbers from 1 to 10.

#### 17. Ստեղծեք 1-ից 10 պատահական թվերով լցված (3, 5) չափերով numpy array։

In [17]:
np.random.choice(range(1, 10), size=(3, 5))

array([[5, 3, 1, 6, 7],
       [4, 3, 7, 9, 4],
       [7, 4, 1, 8, 1]])

#### 18. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

#### 18. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [18]:
x = np.zeros(10)
x[5] = 3
x

array([0., 0., 0., 0., 0., 3., 0., 0., 0., 0.])

#### 19. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

#### 19. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [19]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 20. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array. 

#### 20. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [20]:
def change(arr):
    while (np.average(arr) >= 5):
        arr = arr // 2
    else:
        return arr


x = np.arange(20, 40)
print(x)

y = change(x)
print(y)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4]


#### 21. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an inputand returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

#### 21. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [21]:
def GetMatrixColumns(matrix):
    listOfMatrixCol = []
    for i in range(matrix.shape[1]):
        listOfMatrixCol.append(matrix[:,i])
    return listOfMatrixCol

matrix2 = np.random.randint(10, size = (5,4))
print(matrix2)
cols = GetMatrixColumns(matrix2)
print(cols)

[[6 0 5 7]
 [6 5 6 0]
 [6 2 6 7]
 [5 3 5 5]
 [2 0 2 1]]
[array([6, 6, 6, 5, 2]), array([0, 5, 2, 3, 0]), array([5, 6, 6, 5, 2]), array([7, 0, 7, 5, 1])]


In [22]:
def GetMatrixRows(matrix):
    listOfMatrixRows = []
    for i in range(matrix.shape[0]):
        listOfMatrixRows.append(matrix[i,:])
    return listOfMatrixRows

matrix2 = np.random.randint(10, size = (5,4))
print(matrix2)
rows = GetMatrixRows(matrix2)

print(rows)

[[3 3 9 4]
 [0 0 6 1]
 [8 0 3 5]
 [6 0 7 0]
 [2 4 2 6]]
[array([3, 3, 9, 4]), array([0, 0, 6, 1]), array([8, 0, 3, 5]), array([6, 0, 7, 0]), array([2, 4, 2, 6])]
